name: Build GTK3 App (64-bit)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-libjpeg-turbo
          mingw-w64-x86_64-fribidi
          mingw-w64-x86_64-adwaita-icon-theme
          mingw-w64-x86_64-hicolor-icon-theme
          mingw-w64-x86_64-librsvg

    - name: Build the app
      shell: msys2 {0}
      run: |
        g++ -mwindows -std=c++17 -o app.exe main.cpp `pkg-config --cflags --libs gtk+-3.0`
    
    - name: Prepare bundle folder
      shell: msys2 {0}
      run: |
        mkdir -p bundle/bin
        cp app.exe bundle/bin/

        # Copy DLLs
        cp /mingw64/bin/*.dll bundle/bin/

        # Copy GTK theme
        mkdir -p bundle/share/themes/
        cp -r /mingw64/share/themes/Adwaita bundle/share/themes/
        cp -r /mingw64/share/icons/hicolor bundle/share/icons/
        cp -r /mingw64/share/icons/Adwaita bundle/share/icons/
        cp -r /mingw64/etc bundle/etc

        # Optional: Copy GTK config files if needed
        cp -r /mingw64/share/gtk-3.0 bundle/share/

    - name: Upload bundle artifact
      uses: actions/upload-artifact@v4
      with:
        name: gtk3-windows-bundle
        path: bundle/
        compression-level: 6
