name: Build GTK App with Theme Support

on:
  push:
    paths:
      - '**.cpp'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install MSYS2 with GTK3, themes, JPEG, FriBidi
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-libjpeg-turbo
          mingw-w64-x86_64-fribidi
          mingw-w64-x86_64-adwaita-icon-theme
          mingw-w64-x86_64-hicolor-icon-theme
          mingw-w64-x86_64-gtk3-theme-adwaita
          mingw-w64-x86_64-librsvg
          mingw-w64-x86_64-glib2
          mingw-w64-x86_64-pkg-config

    - name: Build executable
      shell: msys2 {0}
      run: |
        g++ main.cpp -o gtk_native_window.exe \
          `pkg-config --cflags --libs gtk+-3.0 fribidi libjpeg` \
          -mwindows

    - name: Create portable bundle
      shell: msys2 {0}
      run: |
        mkdir -p bundle/share/themes
        mkdir -p bundle/share/icons

        cp gtk_native_window.exe bundle/

        # Copy runtime DLLs
        ldd gtk_native_window.exe | grep '/mingw64/bin/' | awk '{print $3}' | xargs -I{} cp -u {} bundle/

        # Copy GTK theme files
        cp -r /mingw64/share/themes/Adwaita bundle/share/themes/
        cp -r /mingw64/share/themes/Adwaita-dark bundle/share/themes/

        # Copy icon themes
        cp -r /mingw64/share/icons/Adwaita bundle/share/icons/
        cp -r /mingw64/share/icons/hicolor bundle/share/icons/

        # Optional: copy GTK's settings.ini to enable theme usage
        mkdir -p bundle/etc/gtk-3.0
        echo '[Settings]' > bundle/etc/gtk-3.0/settings.ini
        echo 'gtk-theme-name=Adwaita' >> bundle/etc/gtk-3.0/settings.ini
        echo 'gtk-application-prefer-dark-theme=1' >> bundle/etc/gtk-3.0/settings.ini

    - name: Zip the bundle
      run: |
        powershell Compress-Archive -Path bundle\* -DestinationPath gtk_native_window_bundle.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gtk-native-bundle-x64
        path: gtk_native_window_bundle.zip
