name: Build GTK Windows App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-fribidi
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-adwaita-icon-theme
            mingw-w64-x86_64-hicolor-icon-theme
            mingw-w64-x86_64-librsvg
          msystem: MINGW64

      - name: Build executable
        shell: msys2 {0}
        run: |
          g++ -std=c++17 -mwindows -Wall -O2 main.cpp -o app.exe \
            `pkg-config --cflags --libs gtk+-3.0` \
            -ldwmapi

      - name: Create portable bundle
        shell: msys2 {0}
        run: |
          mkdir -p bundle/bin
          mkdir -p bundle/share/icons
          mkdir -p bundle/share/themes/Adwaita/gtk-3.0/
          mkdir -p bundle/etc/gtk-3.0/

          cp app.exe bundle/

          # Copy required DLLs
          cp /mingw64/bin/*.dll bundle/bin/

          # Copy Adwaita theme files
          cp /mingw64/share/icons/Adwaita/icon-theme.cache bundle/share/icons/Adwaita/ || true
          cp -r /mingw64/share/icons/Adwaita bundle/share/icons/

          # Copy Adwaita GTK theme CSS from known fallback locations
          cp /mingw64/share/themes/Adwaita/gtk-3.0/gtk.css bundle/share/themes/Adwaita/gtk-3.0/ || true
          cp /mingw64/share/themes/Adwaita/gtk-3.0/gtk-dark.css bundle/share/themes/Adwaita/gtk-3.0/ || true

          # Fallback: Try to pull from "Default" or "MS-Windows" if Adwaita missing
          cp /mingw64/share/themes/Default/gtk-3.0/* bundle/share/themes/Adwaita/gtk-3.0/ || true
          cp /mingw64/share/themes/MS-Windows/gtk-3.0/* bundle/share/themes/Adwaita/gtk-3.0/ || true

          # Write settings.ini
          echo '[Settings]' > bundle/etc/gtk-3.0/settings.ini
          echo 'gtk-theme-name=Adwaita' >> bundle/etc/gtk-3.0/settings.ini
          echo 'gtk-application-prefer-dark-theme=1' >> bundle/etc/gtk-3.0/settings.ini

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v3
        with:
          name: gtk-bundle
          path: bundle/
