name: Build Native GTK Window (Windows)

on:
  push:
    paths:
      - '**.cpp'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-pkg-config
          msystem: MINGW64

      - name: Build with g++
        shell: msys2 {0}
        run: |
          g++ main.cpp -o gtk_native_window.exe \
            `pkg-config --cflags --libs gtk+-3.0` \
            -mwindows

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gtk-native-window-exe
          path: gtk_native_window.exe
